spring.application.name=emart
server.servlet.context-path=/emart

spring.datasource.url=jdbc:postgresql://localhost:5432/emart
spring.datasource.username=pguser
spring.datasource.password=pguser
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.name=HelloUser
spring.security.user.password = admin123